config/routes.rb
CraiglistRails::Application.routes.draw do

  resources :categories, only: [:index, :show] do
    resources :posts
  end

  root to: "categories#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :description, presence: true, uniqueness: true
  attr_accessible :description

  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :description, :email, :secure_email, :rent, :area, :key, :category
  validates_uniqueness_of :title, :description
  attr_accessible :title, :description, :email, :secure_email, :rent, :area, :key, :category

  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @category = Category.find(params[:category_id])
    @posts = @category.posts

    @errors = flash[:errors] unless flash[:errors].nil? || flash[:errors].empty?
  end

  def new
    @category = Category.find(params[:category_id])
    @post = Post.new
  end

  def create
    @category = Category.find(params[:category_id])
    @post = Post.create( {
                  category: @category,
                  title: params[:post][:title],
                  description: params[:post][:description],
                  email: params[:post][:email],
                  secure_email: "fjf8932983hiufewf28y9@craigslistjr.com",
                  rent: params[:post][:rent],
                  area: params[:post][:area],
                  key: "wzdzihu7832" } )

    flash[:errors] = @post.errors.full_messages
    redirect_to category_posts_path(@category.id)
  end

  def show
    @category = Category.find(params[:category_id])
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<div>
  <h3>Housing</h3>
  <% unless @categories.nil? %>
    <% @categories.each do |category| %>
      <li><%= link_to category.description, category_posts_path(category) %></li>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CraiglistRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <h2>Craigslist Jr.</h2>
<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<div>
  <h3><%= link_to "Housing", root_path %> < <%= @category.description %></h3>
  <p><%= link_to "Create New Post", new_category_post_path(@category.id) %><p>
  <% unless @posts.nil? %>
      <% @posts.each do |post| %>
        <li><%= link_to post.description, category_post_path(@category, post) %></li>
      <% end %>
    <% end %>
</div>

<p><%= @errors %></p>

app/views/posts/new.html.erb
<div>
  <h3><%= link_to "Housing", root_path %> < <%= link_to @category.description, category_posts_path(@category)  %> < New Posting </h3>

  <%= form_for @post, url: {action: "create" } do |f| %>
    <%= f.label :title %></br>
    <%= f.text_field :title %></br>
        </br>
    <%= f.label :rent %></br>
    <%= f.text_field :rent %></br>
        </br>
    <%= f.label :area %></br>
    <%= f.text_field :area %></br>
        </br>
    <%= f.label :description %></br>
    <%= f.text_area :description, size: "60x12" %>
        </br>
    <%= f.label :email %></br>
    <%= f.text_field :email %></br>
        </br>
    <%= f.submit %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div>
  <h3><%= link_to "Housing", root_path %> < <%= link_to @category.description, category_posts_path(@category)  %> < <%= @post.title %> - $<%= @post.rent %> - <%= @post.area %>sq.ft.</h3>

  <p><%= @post.description%></p>
  <p>Reply to: <%= @post.secure_email %></p>
</div>